baseURL = 'https://matthew-nimmo.github.io/mining-ds/'
locale = 'en-us'
title = 'mining-ds'
defaultContentLanguage = "en"
archetypeFormat = "yaml"
canonifyURLs = true
relativeURLs = false 

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"
  repository = "repositories"
